spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fmmall?useUnicode=true&characterEncoding=utf-8&useSSL=false
      password: root
      username: root

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yilei.lei.entity
  configuration:
    # ??????
    map-underscore-to-camel-case: false
#?????????Debug
logging:
  level:
    com.jd.mapper: debug

